# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc414c52b400a13519833e5ee4cac357"
name = "data-sync-assistant"
handle = "data-sync-assistant"
application_url = "https://mood-wallet-halloween-comparison.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mood-wallet-halloween-comparison.trycloudflare.com/auth/callback",
  "https://mood-wallet-halloween-comparison.trycloudflare.com/auth/shopify/callback",
  "https://mood-wallet-halloween-comparison.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
