# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc414c52b400a13519833e5ee4cac357"
name = "data-sync-assistant"
handle = "data-sync-assistant"
application_url = "https://bradford-canal-statistical-physicians.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_price_rules,read_discounts,write_discounts,read_customers,read_orders,read_products,write_customers,write_products"

[auth]
redirect_urls = [
  "https://bradford-canal-statistical-physicians.trycloudflare.com/auth/callback",
  "https://bradford-canal-statistical-physicians.trycloudflare.com/auth/shopify/callback",
  "https://bradford-canal-statistical-physicians.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
